//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProviderApplication.ProviderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBusDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetBusDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNameField;
        
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BusId {
            get {
                return this.BusIdField;
            }
            set {
                if ((this.BusIdField.Equals(value) != true)) {
                    this.BusIdField = value;
                    this.RaisePropertyChanged("BusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BusName {
            get {
                return this.BusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNameField, value) != true)) {
                    this.BusNameField = value;
                    this.RaisePropertyChanged("BusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BusNo {
            get {
                return this.BusNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNoField, value) != true)) {
                    this.BusNoField = value;
                    this.RaisePropertyChanged("BusNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCityDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetCityDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CityState {
            get {
                return this.CityStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CityStateField, value) != true)) {
                    this.CityStateField = value;
                    this.RaisePropertyChanged("CityState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TimeSpan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRouteDetails_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetRouteDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RouteIdField;
        
        private int BusIdField;
        
        private int SourceIdField;
        
        private int DestinationIdField;
        
        private System.DateTime DateOfJourneyField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNoField;
        
        private System.Nullable<int> AvailableSeatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RouteId {
            get {
                return this.RouteIdField;
            }
            set {
                if ((this.RouteIdField.Equals(value) != true)) {
                    this.RouteIdField = value;
                    this.RaisePropertyChanged("RouteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int BusId {
            get {
                return this.BusIdField;
            }
            set {
                if ((this.BusIdField.Equals(value) != true)) {
                    this.BusIdField = value;
                    this.RaisePropertyChanged("BusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DestinationId {
            get {
                return this.DestinationIdField;
            }
            set {
                if ((this.DestinationIdField.Equals(value) != true)) {
                    this.DestinationIdField = value;
                    this.RaisePropertyChanged("DestinationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DateOfJourney {
            get {
                return this.DateOfJourneyField;
            }
            set {
                if ((this.DateOfJourneyField.Equals(value) != true)) {
                    this.DateOfJourneyField = value;
                    this.RaisePropertyChanged("DateOfJourney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalTimeField, value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureTimeField, value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BusName {
            get {
                return this.BusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNameField, value) != true)) {
                    this.BusNameField = value;
                    this.RaisePropertyChanged("BusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string BusNo {
            get {
                return this.BusNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNoField, value) != true)) {
                    this.BusNoField = value;
                    this.RaisePropertyChanged("BusNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> AvailableSeats {
            get {
                return this.AvailableSeatsField;
            }
            set {
                if ((this.AvailableSeatsField.Equals(value) != true)) {
                    this.AvailableSeatsField = value;
                    this.RaisePropertyChanged("AvailableSeats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBookingStatus_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetBookingStatus_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BusIdField;
        
        private int SeatNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeatTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BusId {
            get {
                return this.BusIdField;
            }
            set {
                if ((this.BusIdField.Equals(value) != true)) {
                    this.BusIdField = value;
                    this.RaisePropertyChanged("BusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SeatNo {
            get {
                return this.SeatNoField;
            }
            set {
                if ((this.SeatNoField.Equals(value) != true)) {
                    this.SeatNoField = value;
                    this.RaisePropertyChanged("SeatNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SeatType {
            get {
                return this.SeatTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatTypeField, value) != true)) {
                    this.SeatTypeField = value;
                    this.RaisePropertyChanged("SeatType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProviderServiceReference.ProvidersWebServiceSoap")]
    public interface ProvidersWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name busName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBusDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse InsertBusDetails(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBusDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse> InsertBusDetailsAsync(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBus", ReplyAction="*")]
        bool DeleteBus(int busId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteBusAsync(int busId);
        
        // CODEGEN: Generating message contract since element name seatStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookSeat", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.BookSeatResponse BookSeat(BusProviderApplication.ProviderServiceReference.BookSeatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookSeat", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.BookSeatResponse> BookSeatAsync(BusProviderApplication.ProviderServiceReference.BookSeatRequest request);
        
        // CODEGEN: Generating message contract since element name seatType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeSeatType", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse ChangeSeatType(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeSeatType", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse> ChangeSeatTypeAsync(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request);
        
        // CODEGEN: Generating message contract since element name GetBusDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBusDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.GetBusDetailsResponse GetBusDetails(BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBusDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetBusDetailsResponse> GetBusDetailsAsync(BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name city from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCityDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.AddCityDetailsResponse AddCityDetails(BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCityDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.AddCityDetailsResponse> AddCityDetailsAsync(BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetCityDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.GetCityDetailsResponse GetCityDetails(BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetCityDetailsResponse> GetCityDetailsAsync(BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name arrivalTime from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRouteDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponse AddRouteDetails(BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRouteDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponse> AddRouteDetailsAsync(BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetRouteDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteDetails", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponse GetRouteDetails(BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRouteDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponse> GetRouteDetailsAsync(BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetBookingStatusesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookingStatuses", ReplyAction="*")]
        BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponse GetBookingStatuses(BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookingStatuses", ReplyAction="*")]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponse> GetBookingStatusesAsync(BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBusDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBusDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody Body;
        
        public InsertBusDetailsRequest() {
        }
        
        public InsertBusDetailsRequest(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertBusDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int capacity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string busNo;
        
        public InsertBusDetailsRequestBody() {
        }
        
        public InsertBusDetailsRequestBody(string busName, int capacity, string type, string busNo) {
            this.busName = busName;
            this.capacity = capacity;
            this.type = type;
            this.busNo = busNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBusDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBusDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponseBody Body;
        
        public InsertBusDetailsResponse() {
        }
        
        public InsertBusDetailsResponse(BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertBusDetailsResponseBody {
        
        public InsertBusDetailsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookSeatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookSeat", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.BookSeatRequestBody Body;
        
        public BookSeatRequest() {
        }
        
        public BookSeatRequest(BusProviderApplication.ProviderServiceReference.BookSeatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookSeatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int seatNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int busId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string seatStatus;
        
        public BookSeatRequestBody() {
        }
        
        public BookSeatRequestBody(int seatNo, int busId, string seatStatus) {
            this.seatNo = seatNo;
            this.busId = busId;
            this.seatStatus = seatStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookSeatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookSeatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.BookSeatResponseBody Body;
        
        public BookSeatResponse() {
        }
        
        public BookSeatResponse(BusProviderApplication.ProviderServiceReference.BookSeatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookSeatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool BookSeatResult;
        
        public BookSeatResponseBody() {
        }
        
        public BookSeatResponseBody(bool BookSeatResult) {
            this.BookSeatResult = BookSeatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeSeatTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeSeatType", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody Body;
        
        public ChangeSeatTypeRequest() {
        }
        
        public ChangeSeatTypeRequest(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeSeatTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int seatNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int busId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string seatType;
        
        public ChangeSeatTypeRequestBody() {
        }
        
        public ChangeSeatTypeRequestBody(int seatNo, int busId, string seatType) {
            this.seatNo = seatNo;
            this.busId = busId;
            this.seatType = seatType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeSeatTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeSeatTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponseBody Body;
        
        public ChangeSeatTypeResponse() {
        }
        
        public ChangeSeatTypeResponse(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeSeatTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangeSeatTypeResult;
        
        public ChangeSeatTypeResponseBody() {
        }
        
        public ChangeSeatTypeResponseBody(bool ChangeSeatTypeResult) {
            this.ChangeSeatTypeResult = ChangeSeatTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBusDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBusDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetBusDetailsRequestBody Body;
        
        public GetBusDetailsRequest() {
        }
        
        public GetBusDetailsRequest(BusProviderApplication.ProviderServiceReference.GetBusDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBusDetailsRequestBody {
        
        public GetBusDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBusDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBusDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetBusDetailsResponseBody Body;
        
        public GetBusDetailsResponse() {
        }
        
        public GetBusDetailsResponse(BusProviderApplication.ProviderServiceReference.GetBusDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBusDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetBusDetails_Result[] GetBusDetailsResult;
        
        public GetBusDetailsResponseBody() {
        }
        
        public GetBusDetailsResponseBody(BusProviderApplication.ProviderServiceReference.GetBusDetails_Result[] GetBusDetailsResult) {
            this.GetBusDetailsResult = GetBusDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCityDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCityDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.AddCityDetailsRequestBody Body;
        
        public AddCityDetailsRequest() {
        }
        
        public AddCityDetailsRequest(BusProviderApplication.ProviderServiceReference.AddCityDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCityDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string state;
        
        public AddCityDetailsRequestBody() {
        }
        
        public AddCityDetailsRequestBody(string city, string state) {
            this.city = city;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCityDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCityDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.AddCityDetailsResponseBody Body;
        
        public AddCityDetailsResponse() {
        }
        
        public AddCityDetailsResponse(BusProviderApplication.ProviderServiceReference.AddCityDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCityDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCityDetailsResult;
        
        public AddCityDetailsResponseBody() {
        }
        
        public AddCityDetailsResponseBody(bool AddCityDetailsResult) {
            this.AddCityDetailsResult = AddCityDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetCityDetailsRequestBody Body;
        
        public GetCityDetailsRequest() {
        }
        
        public GetCityDetailsRequest(BusProviderApplication.ProviderServiceReference.GetCityDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCityDetailsRequestBody {
        
        public GetCityDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetCityDetailsResponseBody Body;
        
        public GetCityDetailsResponse() {
        }
        
        public GetCityDetailsResponse(BusProviderApplication.ProviderServiceReference.GetCityDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetCityDetails_Result[] GetCityDetailsResult;
        
        public GetCityDetailsResponseBody() {
        }
        
        public GetCityDetailsResponseBody(BusProviderApplication.ProviderServiceReference.GetCityDetails_Result[] GetCityDetailsResult) {
            this.GetCityDetailsResult = GetCityDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRouteDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRouteDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequestBody Body;
        
        public AddRouteDetailsRequest() {
        }
        
        public AddRouteDetailsRequest(BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRouteDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int busId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sourceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int destinationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateOfJourney;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public BusProviderApplication.ProviderServiceReference.TimeSpan arrivalTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BusProviderApplication.ProviderServiceReference.TimeSpan departureTime;
        
        public AddRouteDetailsRequestBody() {
        }
        
        public AddRouteDetailsRequestBody(int busId, int sourceId, int destinationId, System.DateTime dateOfJourney, double price, BusProviderApplication.ProviderServiceReference.TimeSpan arrivalTime, BusProviderApplication.ProviderServiceReference.TimeSpan departureTime) {
            this.busId = busId;
            this.sourceId = sourceId;
            this.destinationId = destinationId;
            this.dateOfJourney = dateOfJourney;
            this.price = price;
            this.arrivalTime = arrivalTime;
            this.departureTime = departureTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRouteDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRouteDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponseBody Body;
        
        public AddRouteDetailsResponse() {
        }
        
        public AddRouteDetailsResponse(BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRouteDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddRouteDetailsResult;
        
        public AddRouteDetailsResponseBody() {
        }
        
        public AddRouteDetailsResponseBody(bool AddRouteDetailsResult) {
            this.AddRouteDetailsResult = AddRouteDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteDetails", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequestBody Body;
        
        public GetRouteDetailsRequest() {
        }
        
        public GetRouteDetailsRequest(BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sourceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int destinationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dateOfJourney;
        
        public GetRouteDetailsRequestBody() {
        }
        
        public GetRouteDetailsRequestBody(int sourceId, int destinationId, System.DateTime dateOfJourney) {
            this.sourceId = sourceId;
            this.destinationId = destinationId;
            this.dateOfJourney = dateOfJourney;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponseBody Body;
        
        public GetRouteDetailsResponse() {
        }
        
        public GetRouteDetailsResponse(BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRouteDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetRouteDetails_Result[] GetRouteDetailsResult;
        
        public GetRouteDetailsResponseBody() {
        }
        
        public GetRouteDetailsResponseBody(BusProviderApplication.ProviderServiceReference.GetRouteDetails_Result[] GetRouteDetailsResult) {
            this.GetRouteDetailsResult = GetRouteDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingStatusesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingStatuses", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequestBody Body;
        
        public GetBookingStatusesRequest() {
        }
        
        public GetBookingStatusesRequest(BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookingStatusesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int busId;
        
        public GetBookingStatusesRequestBody() {
        }
        
        public GetBookingStatusesRequestBody(int busId) {
            this.busId = busId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookingStatusesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookingStatusesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponseBody Body;
        
        public GetBookingStatusesResponse() {
        }
        
        public GetBookingStatusesResponse(BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookingStatusesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BusProviderApplication.ProviderServiceReference.GetBookingStatus_Result[] GetBookingStatusesResult;
        
        public GetBookingStatusesResponseBody() {
        }
        
        public GetBookingStatusesResponseBody(BusProviderApplication.ProviderServiceReference.GetBookingStatus_Result[] GetBookingStatusesResult) {
            this.GetBookingStatusesResult = GetBookingStatusesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProvidersWebServiceSoapChannel : BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProvidersWebServiceSoapClient : System.ServiceModel.ClientBase<BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap>, BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap {
        
        public ProvidersWebServiceSoapClient() {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvidersWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.InsertBusDetails(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request) {
            return base.Channel.InsertBusDetails(request);
        }
        
        public void InsertBusDetails(string busName, int capacity, string type, string busNo) {
            BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody();
            inValue.Body.busName = busName;
            inValue.Body.capacity = capacity;
            inValue.Body.type = type;
            inValue.Body.busNo = busNo;
            BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertBusDetails(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.InsertBusDetailsAsync(BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest request) {
            return base.Channel.InsertBusDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.InsertBusDetailsResponse> InsertBusDetailsAsync(string busName, int capacity, string type, string busNo) {
            BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.InsertBusDetailsRequestBody();
            inValue.Body.busName = busName;
            inValue.Body.capacity = capacity;
            inValue.Body.type = type;
            inValue.Body.busNo = busNo;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).InsertBusDetailsAsync(inValue);
        }
        
        public bool DeleteBus(int busId) {
            return base.Channel.DeleteBus(busId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBusAsync(int busId) {
            return base.Channel.DeleteBusAsync(busId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.BookSeatResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.BookSeat(BusProviderApplication.ProviderServiceReference.BookSeatRequest request) {
            return base.Channel.BookSeat(request);
        }
        
        public bool BookSeat(int seatNo, int busId, string seatStatus) {
            BusProviderApplication.ProviderServiceReference.BookSeatRequest inValue = new BusProviderApplication.ProviderServiceReference.BookSeatRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.BookSeatRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatStatus = seatStatus;
            BusProviderApplication.ProviderServiceReference.BookSeatResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).BookSeat(inValue);
            return retVal.Body.BookSeatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.BookSeatResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.BookSeatAsync(BusProviderApplication.ProviderServiceReference.BookSeatRequest request) {
            return base.Channel.BookSeatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.BookSeatResponse> BookSeatAsync(int seatNo, int busId, string seatStatus) {
            BusProviderApplication.ProviderServiceReference.BookSeatRequest inValue = new BusProviderApplication.ProviderServiceReference.BookSeatRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.BookSeatRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatStatus = seatStatus;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).BookSeatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.ChangeSeatType(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request) {
            return base.Channel.ChangeSeatType(request);
        }
        
        public bool ChangeSeatType(int seatNo, int busId, string seatType) {
            BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest inValue = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatType = seatType;
            BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).ChangeSeatType(inValue);
            return retVal.Body.ChangeSeatTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.ChangeSeatTypeAsync(BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest request) {
            return base.Channel.ChangeSeatTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.ChangeSeatTypeResponse> ChangeSeatTypeAsync(int seatNo, int busId, string seatType) {
            BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest inValue = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.ChangeSeatTypeRequestBody();
            inValue.Body.seatNo = seatNo;
            inValue.Body.busId = busId;
            inValue.Body.seatType = seatType;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).ChangeSeatTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.GetBusDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetBusDetails(BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest request) {
            return base.Channel.GetBusDetails(request);
        }
        
        public BusProviderApplication.ProviderServiceReference.GetBusDetails_Result[] GetBusDetails() {
            BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetBusDetailsRequestBody();
            BusProviderApplication.ProviderServiceReference.GetBusDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetBusDetails(inValue);
            return retVal.Body.GetBusDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetBusDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetBusDetailsAsync(BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest request) {
            return base.Channel.GetBusDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetBusDetailsResponse> GetBusDetailsAsync() {
            BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetBusDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetBusDetailsRequestBody();
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetBusDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.AddCityDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.AddCityDetails(BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest request) {
            return base.Channel.AddCityDetails(request);
        }
        
        public bool AddCityDetails(string city, string state) {
            BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.AddCityDetailsRequestBody();
            inValue.Body.city = city;
            inValue.Body.state = state;
            BusProviderApplication.ProviderServiceReference.AddCityDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).AddCityDetails(inValue);
            return retVal.Body.AddCityDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.AddCityDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.AddCityDetailsAsync(BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest request) {
            return base.Channel.AddCityDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.AddCityDetailsResponse> AddCityDetailsAsync(string city, string state) {
            BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.AddCityDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.AddCityDetailsRequestBody();
            inValue.Body.city = city;
            inValue.Body.state = state;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).AddCityDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.GetCityDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetCityDetails(BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest request) {
            return base.Channel.GetCityDetails(request);
        }
        
        public BusProviderApplication.ProviderServiceReference.GetCityDetails_Result[] GetCityDetails() {
            BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetCityDetailsRequestBody();
            BusProviderApplication.ProviderServiceReference.GetCityDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetCityDetails(inValue);
            return retVal.Body.GetCityDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetCityDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetCityDetailsAsync(BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest request) {
            return base.Channel.GetCityDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetCityDetailsResponse> GetCityDetailsAsync() {
            BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetCityDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetCityDetailsRequestBody();
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetCityDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.AddRouteDetails(BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest request) {
            return base.Channel.AddRouteDetails(request);
        }
        
        public bool AddRouteDetails(int busId, int sourceId, int destinationId, System.DateTime dateOfJourney, double price, BusProviderApplication.ProviderServiceReference.TimeSpan arrivalTime, BusProviderApplication.ProviderServiceReference.TimeSpan departureTime) {
            BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequestBody();
            inValue.Body.busId = busId;
            inValue.Body.sourceId = sourceId;
            inValue.Body.destinationId = destinationId;
            inValue.Body.dateOfJourney = dateOfJourney;
            inValue.Body.price = price;
            inValue.Body.arrivalTime = arrivalTime;
            inValue.Body.departureTime = departureTime;
            BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).AddRouteDetails(inValue);
            return retVal.Body.AddRouteDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.AddRouteDetailsAsync(BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest request) {
            return base.Channel.AddRouteDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.AddRouteDetailsResponse> AddRouteDetailsAsync(int busId, int sourceId, int destinationId, System.DateTime dateOfJourney, double price, BusProviderApplication.ProviderServiceReference.TimeSpan arrivalTime, BusProviderApplication.ProviderServiceReference.TimeSpan departureTime) {
            BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.AddRouteDetailsRequestBody();
            inValue.Body.busId = busId;
            inValue.Body.sourceId = sourceId;
            inValue.Body.destinationId = destinationId;
            inValue.Body.dateOfJourney = dateOfJourney;
            inValue.Body.price = price;
            inValue.Body.arrivalTime = arrivalTime;
            inValue.Body.departureTime = departureTime;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).AddRouteDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetRouteDetails(BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest request) {
            return base.Channel.GetRouteDetails(request);
        }
        
        public BusProviderApplication.ProviderServiceReference.GetRouteDetails_Result[] GetRouteDetails(int sourceId, int destinationId, System.DateTime dateOfJourney) {
            BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequestBody();
            inValue.Body.sourceId = sourceId;
            inValue.Body.destinationId = destinationId;
            inValue.Body.dateOfJourney = dateOfJourney;
            BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetRouteDetails(inValue);
            return retVal.Body.GetRouteDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetRouteDetailsAsync(BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest request) {
            return base.Channel.GetRouteDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetRouteDetailsResponse> GetRouteDetailsAsync(int sourceId, int destinationId, System.DateTime dateOfJourney) {
            BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest inValue = new BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetRouteDetailsRequestBody();
            inValue.Body.sourceId = sourceId;
            inValue.Body.destinationId = destinationId;
            inValue.Body.dateOfJourney = dateOfJourney;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetRouteDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponse BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetBookingStatuses(BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest request) {
            return base.Channel.GetBookingStatuses(request);
        }
        
        public BusProviderApplication.ProviderServiceReference.GetBookingStatus_Result[] GetBookingStatuses(int busId) {
            BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest inValue = new BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequestBody();
            inValue.Body.busId = busId;
            BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponse retVal = ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetBookingStatuses(inValue);
            return retVal.Body.GetBookingStatusesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponse> BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap.GetBookingStatusesAsync(BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest request) {
            return base.Channel.GetBookingStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusProviderApplication.ProviderServiceReference.GetBookingStatusesResponse> GetBookingStatusesAsync(int busId) {
            BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest inValue = new BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequest();
            inValue.Body = new BusProviderApplication.ProviderServiceReference.GetBookingStatusesRequestBody();
            inValue.Body.busId = busId;
            return ((BusProviderApplication.ProviderServiceReference.ProvidersWebServiceSoap)(this)).GetBookingStatusesAsync(inValue);
        }
    }
}
